### PR TITLE
Added support for spot cleaning, added repeat and 4x4 mode for spot cleaning

### PR DESCRIPTION
**Pull request by nicoh88**
Repeat and 4x4 mode are not persistent - node-botvac api not supported. After a reboot of homebridge set it to off/false - use it for spot cleaning in compination with homekit scenes or automations.

### CODE REVIEW

**Comment by naofireblade** [comment]
Hey thank you very much for this pull request. I will review and merge this in the next couple of days.

**Comment by ifeign** [comment]
Any updates on this PR? Once we get spot cleaning and zone cleaning we'll pretty much be feature complete in Homekit

**Comment by naofireblade** [comment]
Will merge it in the next release.

**Comment by naofireblade** [comment]
Merged the readme, will take a look in the code and add some cool features.

**Comment by naofireblade** [comment]
Added the spot cleaning feature with individual size for D7

**Pull request merged**
