### PR TITLE
Add display language selection

### PR DESCRIPTION
**Pull request by himbeles**
Adds Language selection (also via homebridge UI) for English, German, French. 
Picked from https://github.com/himbeles/homebridge-kobold .
Solves #59 .

### CODE REVIEW

**Comment by naofireblade** [comment]
Thanks for the PR! I'm currently rewriting the complete plugin for dynamic platform and typescript. Could you adapt your PR for the branch https://github.com/naofireblade/homebridge-neato/tree/dynamic-platform ?

**Comment by naofireblade** [comment]
Also for easier PRs from users it would be cool to have the language properties in separate files.

**Comment by himbeles** [comment]
Nice! Also I see mostly async/await instead of callbacks now 👍 .
Don't have too much free time though before real-life home office starts :) 
Will try on one of the coming weekends.

**Comment by naofireblade** [comment]
Awesome. I will release a beta as soon as my PRs for the node-botvac library get merged.

**Comment by himbeles** [comment]
Closed in favor of #66

**Pull request closed without merging**
